---
# This module helps to understand debug module and lookup plugins.

# HEADER SECTION
 - name: This playbook will create a file
   hosts: webservers
   vars:
     myname: Goutham
     motd_value: "{{ lookup('file', '/opt/motd') }}"

# TASK SECTION
   tasks:
     - name: This task gets executed when we run the tag install
       debug:
         var: myname
       tags:
       - install

     - name: This task executed when we run tag install
       file:
         path: /opt/test.txt
         state: touch
       tags:
       - install

     - name: This task gets executed when we run the tag deploy
       debug:
         msg: "motd value is {{ motd_value }}"
       tags:
       - deploy
