---
# This Playbook will define vairables and use them across the code

# HEADER SECTION
 - name: This play will install a package and copy a file
   hosts: webservers
   serial: "50%"
   become: yes
   max_fail_percentage: 10
   vars:
     mypackage: vim
     myfile: helloworld.yml

# TASK SECTION
   tasks:
     - package:
         name: "{{ mypackage }}"
         state: present

     - copy:
         src: "/home/ec2-user/{{ myfile }}"
         dest: "/opt/{{ myfile }}"
         mode: 0644
