---
# This playbook will download, unzip, install and start Apache Tomcat

# HEADER SECTION
 - name: This playbook will download, unzip, install and start Apache Tomcat
   hosts: webservers
   gather_facts: True
   vars:
     java_apt: openjdk-8-jdk
     java_yum: java-1.8.0-openjdk-devel
     download_url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.82/bin/apache-tomcat-8.5.82.tar.gz
     tomcat: apache-tomcat-8.5.82
     group_name: tomcatadm

# TASK SECTION
   tasks:
     - name: To install java on Ubuntu as its mandatory dependency
       apt:
         name: "{{ java_apt }}"
         state: present
       when: ( ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "18" )

     - name: To install java on EL Linux as its mandatory dependency
       yum:
         name: "{{ java_yum }}"
         state: installed
       when:
         ansible_distribution == "Amazon"

     - name: To create a group
       group:
         name: "{{ group_name }}"
         state: present

     - name: To create a user
       user:
         name: tomcat
         state: present
         groups: "{{ group_name }}"

     - name: to create a dir
       file:
         path: /opt/tomcat_backup
         state: directory
         mode: 0644
         owner: tomcat
         group: "{{ group_name }}"

     - name: To download apache tomcat
       get_url: 
         url: "{{ download_url }}" 
         mode: 0755
         dest: /opt/{{ tomcat }}.tar.gz
         backup: yes
         timeout: 20
         owner: tomcat
         group: tomcatadm

     - name: To untar and unzip the package
       unarchive:
         src: /opt/{{ tomcat }}.tar.gz
         dest: /opt/
         mode: 0755
         remote_src: yes
         owner: tomcat
         group: tomcatadm

     - name: to fetch the server.xml file from remote servers
       fetch:
         src: "/opt/{{ tomcat }}/conf/server.xml"
         dest: /opt/

     - name: To update the apache tomcat config
       copy:
         src: /opt/server.xml
         dest: /opt/apache-tomcat-8.5.82/conf/server.xml
         owner: tomcat
         group: tomcatadm
       ignore_errors: yes

     - name: To start apache tomcat
       command: nohup /opt/apache-tomcat-8.5.82/bin/startup.sh &
